// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"VideoRoom/app/video/internal/dao/internal"
)

// internalVideoTagDao is internal type for wrapping internal DAO implements.
type internalVideoTagDao = *internal.VideoTagDao

// videoTagDao is the data access object for table video_tag.
// You can define custom methods on it to extend its functionality as you wish.
type videoTagDao struct {
	internalVideoTagDao
}

var (
	// VideoTag is globally public accessible object for table video_tag operations.
	VideoTag = videoTagDao{
		internal.NewVideoTagDao(),
	}
)

// Fill with you ideas below.
