// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"VideoRoom/app/video/internal/dao/internal"
)

// internalVideosDao is internal type for wrapping internal DAO implements.
type internalVideosDao = *internal.VideosDao

// videosDao is the data access object for table videos.
// You can define custom methods on it to extend its functionality as you wish.
type videosDao struct {
	internalVideosDao
}

var (
	// Videos is globally public accessible object for table videos operations.
	Videos = videosDao{
		internal.NewVideosDao(),
	}
)

// Fill with you ideas below.
