// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"video_room/app/video_room/internal/dao/internal"
)

// internalRoomsDao is internal type for wrapping internal DAO implements.
type internalRoomsDao = *internal.RoomsDao

// roomsDao is the data access object for table rooms.
// You can define custom methods on it to extend its functionality as you wish.
type roomsDao struct {
	internalRoomsDao
}

var (
	// Rooms is globally public accessible object for table rooms operations.
	Rooms = roomsDao{
		internal.NewRoomsDao(),
	}
)

// Fill with you ideas below.
