// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"video_room/app/video_room/internal/dao/internal"
)

// internalVideoCommentsDao is internal type for wrapping internal DAO implements.
type internalVideoCommentsDao = *internal.VideoCommentsDao

// videoCommentsDao is the data access object for table video_comments.
// You can define custom methods on it to extend its functionality as you wish.
type videoCommentsDao struct {
	internalVideoCommentsDao
}

var (
	// VideoComments is globally public accessible object for table video_comments operations.
	VideoComments = videoCommentsDao{
		internal.NewVideoCommentsDao(),
	}
)

// Fill with you ideas below.
